
services:
  web:
    build: .
    volumes:
      - .:/app
    ports:
      - "8000:8000"
    env_file:
      - .env
    environment:
      - PYTHONUNBUFFERED=1
    command: python manage.py runserver 0.0.0.0:8000
    restart: unless-stopped

  scheduler:
    build: .
    volumes:
      - .:/app
    env_file:
      - .env
    environment:
      - PYTHONUNBUFFERED=1
    command: python manage.py run_scheduler
    depends_on:
      - web
    restart: unless-stopped

volumes:
  static_volume:
  media_volume:
