
services:
  web:
    build: .
    volumes:
      - .:/app
    ports:
      - "8000:7860"
    env_file:
      - .env
    environment:
      - PYTHONUNBUFFERED=1
      - PORT=7860
      - RUN_MIGRATIONS=true
      - RUN_COLLECTSTATIC=true
      - RUN_SCHEDULER=false
    command: /app/entrypoint.sh
    restart: unless-stopped
    shm_size: "2gb"

  scheduler:
    build: .
    volumes:
      - .:/app
    env_file:
      - .env
    environment:
      - PYTHONUNBUFFERED=1
      - RUN_MIGRATIONS=false
      - RUN_COLLECTSTATIC=false
    command: python manage.py run_scheduler
    depends_on:
      - web
    restart: unless-stopped
    shm_size: "2gb"

volumes:
  static_volume:
  media_volume:
