"""
Django settings for automoto project.

Generated by 'django-admin startproject' using Django 5.2.4.

For more information on this file, see
https://docs.djangoproject.com/en/5.2/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/5.2/ref/settings/
"""

import os
from pathlib import Path

from dotenv import load_dotenv

# Load environment variables from .env file
load_dotenv()

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent


def _module_available(module_name: str) -> bool:
    try:
        __import__(module_name)
        return True
    except ImportError:
        return False


def _env_int(name: str, default: int) -> int:
    return int(os.getenv(name, str(default)))


def _env_float(name: str, default: float) -> float:
    return float(os.getenv(name, str(default)))


def _env_csv(name: str, default: str) -> list[str]:
    return [
        item.strip() for item in os.getenv(name, default).split(",") if item.strip()
    ]


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/5.2/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = os.getenv(
    "SECRET_KEY", "django-insecure-f$+&n#ka6y!#wm4#!_pj6i4jc9iqj3b&ch!h!$5-p#mf%w$jfj"
)

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = os.getenv("DEBUG", "True").lower() == "true"

ALLOWED_HOSTS = [
    host.strip()
    for host in os.getenv("ALLOWED_HOSTS", "localhost,127.0.0.1,testserver").split(",")
    if host.strip()
]

CSRF_TRUSTED_ORIGINS = [
    origin.strip()
    for origin in os.getenv("CSRF_TRUSTED_ORIGINS", "").split(",")
    if origin.strip()
]


# Application definition

INSTALLED_APPS = [
    "django.contrib.admin",
    "django.contrib.auth",
    "django.contrib.contenttypes",
    "django.contrib.sessions",
    "django.contrib.messages",
    "django.contrib.staticfiles",
    "accounts",
    "django_apscheduler",
    "job_scraper",
]

ENABLE_DEBUG_TOOLBAR = DEBUG and _module_available("debug_toolbar")
ENABLE_ADMIN_SHELL = DEBUG and _module_available("django_admin_shell")
ENABLE_WHITENOISE = _module_available("whitenoise")

if ENABLE_DEBUG_TOOLBAR:
    INSTALLED_APPS.append("debug_toolbar")

if ENABLE_ADMIN_SHELL:
    INSTALLED_APPS.append("django_admin_shell")

# Enrichment Debug Mode (Minimal Credit Usage)
DEBUG_ENRICHMENT = os.getenv("DEBUG_ENRICHMENT", "True").lower() == "true"

MIDDLEWARE = [
    "django.middleware.security.SecurityMiddleware",
    "django.contrib.sessions.middleware.SessionMiddleware",
    "django.middleware.common.CommonMiddleware",
    "django.middleware.csrf.CsrfViewMiddleware",
    "django.contrib.auth.middleware.AuthenticationMiddleware",
    "accounts.middleware.RequestRateLimitMiddleware",
    "django.contrib.messages.middleware.MessageMiddleware",
    "django.middleware.clickjacking.XFrameOptionsMiddleware",
]

if ENABLE_DEBUG_TOOLBAR:
    MIDDLEWARE.insert(0, "debug_toolbar.middleware.DebugToolbarMiddleware")

if ENABLE_WHITENOISE:
    MIDDLEWARE.insert(1, "whitenoise.middleware.WhiteNoiseMiddleware")

ROOT_URLCONF = "automoto.urls"

TEMPLATES = [
    {
        "BACKEND": "django.template.backends.django.DjangoTemplates",
        "DIRS": [BASE_DIR / "templates"],
        "APP_DIRS": True,
        "OPTIONS": {
            "context_processors": [
                "django.template.context_processors.request",
                "django.contrib.auth.context_processors.auth",
                "django.contrib.messages.context_processors.messages",
            ],
        },
    },
]

WSGI_APPLICATION = "automoto.wsgi.application"


# Database
# https://docs.djangoproject.com/en/5.2/ref/settings/#databases

DATABASES = {
    "default": {
        "ENGINE": "django.db.backends.sqlite3",
        "NAME": os.getenv("SQLITE_PATH", str(BASE_DIR / "db.sqlite3")),
    }
}


# Password validation
# https://docs.djangoproject.com/en/5.2/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        "NAME": "django.contrib.auth.password_validation.UserAttributeSimilarityValidator",
    },
    {
        "NAME": "django.contrib.auth.password_validation.MinimumLengthValidator",
    },
    {
        "NAME": "django.contrib.auth.password_validation.CommonPasswordValidator",
    },
    {
        "NAME": "django.contrib.auth.password_validation.NumericPasswordValidator",
    },
]


# Internationalization
# https://docs.djangoproject.com/en/5.2/topics/i18n/

LANGUAGE_CODE = "en-us"

TIME_ZONE = os.getenv("TIME_ZONE", "UTC")

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/5.2/howto/static-files/

STATIC_URL = "/static/"
STATIC_ROOT = BASE_DIR / "staticfiles"
if ENABLE_WHITENOISE:
    STATICFILES_STORAGE = "whitenoise.storage.CompressedManifestStaticFilesStorage"

# Additional locations of static files
PROJECT_STATIC_DIR = BASE_DIR / "static"
STATICFILES_DIRS = [PROJECT_STATIC_DIR] if PROJECT_STATIC_DIR.exists() else []

# Default primary key field type
# https://docs.djangoproject.com/en/5.2/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = "django.db.models.BigAutoField"
AUTH_USER_MODEL = "accounts.User"
LOGIN_URL = "login"
LOGIN_REDIRECT_URL = "dashboard"
LOGOUT_REDIRECT_URL = "login"
PASSWORD_CHANGE_URL = "password_change"
PASSWORD_CHANGE_REDIRECT_URL = "password_change_done"
SESSION_COOKIE_HTTPONLY = True
SESSION_COOKIE_SAMESITE = "Lax"
CSRF_COOKIE_HTTPONLY = True
CSRF_COOKIE_SAMESITE = "Lax"
SECURE_CONTENT_TYPE_NOSNIFF = True
SECURE_REFERRER_POLICY = "same-origin"
X_FRAME_OPTIONS = "DENY"
SECURE_PROXY_SSL_HEADER = ("HTTP_X_FORWARDED_PROTO", "https")
SECURE_SSL_REDIRECT = (
    not DEBUG and os.getenv("SECURE_SSL_REDIRECT", "False").lower() == "true"
)
SESSION_COOKIE_SECURE = not DEBUG
CSRF_COOKIE_SECURE = not DEBUG
SECURE_HSTS_SECONDS = 31536000 if not DEBUG else 0
SECURE_HSTS_INCLUDE_SUBDOMAINS = not DEBUG
SECURE_HSTS_PRELOAD = not DEBUG
LOGIN_RATE_LIMIT = int(os.getenv("LOGIN_RATE_LIMIT", "5"))
LOGIN_RATE_WINDOW_SECONDS = int(os.getenv("LOGIN_RATE_WINDOW_SECONDS", "300"))
REQUEST_RATE_LIMIT = int(os.getenv("REQUEST_RATE_LIMIT", "240"))
REQUEST_RATE_WINDOW_SECONDS = int(os.getenv("REQUEST_RATE_WINDOW_SECONDS", "60"))
RESULTS_PER_PAGE = _env_int("RESULTS_PER_PAGE", 10)
DEFAULT_SCRAPE_KEYWORDS = os.getenv("DEFAULT_SCRAPE_KEYWORDS", "software contract")
DEFAULT_SCRAPE_LOCATION = os.getenv("DEFAULT_SCRAPE_LOCATION", "us")
DEFAULT_SCRAPE_MAX_PAGES = _env_int("DEFAULT_SCRAPE_MAX_PAGES", 1)
DEFAULT_ENRICHMENT_LIMIT = _env_int("DEFAULT_ENRICHMENT_LIMIT", 10)
API_SCRAPER_TIMEOUT_SECONDS = _env_int("API_SCRAPER_TIMEOUT_SECONDS", 30)
REQUEST_SCRAPER_TIMEOUT_SECONDS = _env_int("REQUEST_SCRAPER_TIMEOUT_SECONDS", 30)
REQUEST_DETAIL_TIMEOUT_SECONDS = _env_int("REQUEST_DETAIL_TIMEOUT_SECONDS", 20)
ANTI_BOT_FAILURE_THRESHOLD = _env_int("ANTI_BOT_FAILURE_THRESHOLD", 3)
ANTI_BOT_COOLDOWN_SECONDS = _env_int("ANTI_BOT_COOLDOWN_SECONDS", 3600)
SCHEDULER_CLEANUP_MAX_AGE_SECONDS = _env_int(
    "SCHEDULER_CLEANUP_MAX_AGE_SECONDS", 604800
)
SCHEDULER_CLEANUP_CRON = os.getenv("SCHEDULER_CLEANUP_CRON", "0 0 * * 1")
STEALTH_WINDOW_WIDTH_MIN = _env_int("STEALTH_WINDOW_WIDTH_MIN", 1200)
STEALTH_WINDOW_WIDTH_MAX = _env_int("STEALTH_WINDOW_WIDTH_MAX", 1920)
STEALTH_WINDOW_HEIGHT_MIN = _env_int("STEALTH_WINDOW_HEIGHT_MIN", 800)
STEALTH_WINDOW_HEIGHT_MAX = _env_int("STEALTH_WINDOW_HEIGHT_MAX", 1080)
STEALTH_WARMUP_SITES = _env_csv(
    "STEALTH_WARMUP_SITES",
    "https://www.google.com/search?q=latest+technology+news,https://en.wikipedia.org/wiki/Main_Page,https://www.bing.com,https://stackoverflow.com",
)
STEALTH_RECONNECT_TIME_SECONDS = _env_int("STEALTH_RECONNECT_TIME_SECONDS", 8)
STEALTH_CAPTCHA_RETRIES = _env_int("STEALTH_CAPTCHA_RETRIES", 2)
REQUEST_PAGE_JITTER_MIN_SECONDS = _env_float("REQUEST_PAGE_JITTER_MIN_SECONDS", 1.2)
REQUEST_PAGE_JITTER_MAX_SECONDS = _env_float("REQUEST_PAGE_JITTER_MAX_SECONDS", 3.0)
REQUEST_DETAIL_JITTER_MIN_SECONDS = _env_float("REQUEST_DETAIL_JITTER_MIN_SECONDS", 0.8)
REQUEST_DETAIL_JITTER_MAX_SECONDS = _env_float("REQUEST_DETAIL_JITTER_MAX_SECONDS", 1.8)
REQUEST_BETWEEN_PAGES_JITTER_MIN_SECONDS = _env_float(
    "REQUEST_BETWEEN_PAGES_JITTER_MIN_SECONDS", 1.0
)
REQUEST_BETWEEN_PAGES_JITTER_MAX_SECONDS = _env_float(
    "REQUEST_BETWEEN_PAGES_JITTER_MAX_SECONDS", 2.4
)
STEALTH_PAGE_JITTER_MIN_SECONDS = _env_float("STEALTH_PAGE_JITTER_MIN_SECONDS", 1.5)
STEALTH_PAGE_JITTER_MAX_SECONDS = _env_float("STEALTH_PAGE_JITTER_MAX_SECONDS", 3.2)
STEALTH_POST_OPEN_JITTER_MIN_SECONDS = _env_float(
    "STEALTH_POST_OPEN_JITTER_MIN_SECONDS", 3.0
)
STEALTH_POST_OPEN_JITTER_MAX_SECONDS = _env_float(
    "STEALTH_POST_OPEN_JITTER_MAX_SECONDS", 5.5
)
STEALTH_WARMUP_PAGE_JITTER_MIN_SECONDS = _env_float(
    "STEALTH_WARMUP_PAGE_JITTER_MIN_SECONDS", 2.0
)
STEALTH_WARMUP_PAGE_JITTER_MAX_SECONDS = _env_float(
    "STEALTH_WARMUP_PAGE_JITTER_MAX_SECONDS", 4.0
)
STEALTH_WARMUP_SCROLL_JITTER_MIN_SECONDS = _env_float(
    "STEALTH_WARMUP_SCROLL_JITTER_MIN_SECONDS", 1.0
)
STEALTH_WARMUP_SCROLL_JITTER_MAX_SECONDS = _env_float(
    "STEALTH_WARMUP_SCROLL_JITTER_MAX_SECONDS", 2.0
)
SEED_DEMO_ADMIN_EMAIL = os.getenv("SEED_DEMO_ADMIN_EMAIL", "admin@example.com")
SEED_DEMO_ADMIN_PASSWORD = os.getenv("SEED_DEMO_ADMIN_PASSWORD", "admin12345")
EMAIL_BACKEND = os.getenv(
    "EMAIL_BACKEND",
    (
        "django.core.mail.backends.console.EmailBackend"
        if DEBUG
        else "django.core.mail.backends.smtp.EmailBackend"
    ),
)
EMAIL_HOST = os.getenv("EMAIL_HOST", "localhost")
EMAIL_PORT = int(os.getenv("EMAIL_PORT", "25"))
EMAIL_HOST_USER = os.getenv("EMAIL_HOST_USER", "")
EMAIL_HOST_PASSWORD = os.getenv("EMAIL_HOST_PASSWORD", "")
EMAIL_USE_TLS = os.getenv("EMAIL_USE_TLS", "False").lower() == "true"
EMAIL_USE_SSL = os.getenv("EMAIL_USE_SSL", "False").lower() == "true"
DEFAULT_FROM_EMAIL = os.getenv("DEFAULT_FROM_EMAIL", "automoto@example.com")
EMAIL_SUBJECT_PREFIX = os.getenv("EMAIL_SUBJECT_PREFIX", "AutoMoto")
SITE_DOMAIN = os.getenv("SITE_DOMAIN", "localhost:8000")

# Media files (User uploaded or generated by scraper)
MEDIA_URL = "/media/"
MEDIA_ROOT = BASE_DIR / "media"


# Debug Toolbar Settings
INTERNAL_IPS = [
    "127.0.0.1",
    "localhost",
]
DEBUG_TOOLBAR_CONFIG = {
    "SHOW_COLLAPSED": True,
}

# Django Admin Shell Settings
ADMIN_SHELL_ONLY_SUPERUSER = True


LOG_LEVEL = os.getenv("LOG_LEVEL", "INFO").upper()
DJANGO_LOG_LEVEL = os.getenv("DJANGO_LOG_LEVEL", "INFO").upper()

LOGGING = {
    "version": 1,
    "disable_existing_loggers": False,
    "filters": {
        "require_debug_true": {"()": "django.utils.log.RequireDebugTrue"},
        "require_debug_false": {"()": "django.utils.log.RequireDebugFalse"},
    },
    "formatters": {
        "dev": {
            "format": "[%(asctime)s] %(levelname)s %(name)s:%(lineno)d - %(message)s",
            "datefmt": "%Y-%m-%d %H:%M:%S",
        },
        "prod": {
            "format": (
                "ts=%(asctime)s level=%(levelname)s logger=%(name)s "
                "line=%(lineno)d module=%(module)s func=%(funcName)s msg=%(message)s"
            ),
            "datefmt": "%Y-%m-%dT%H:%M:%S%z",
        },
    },
    "handlers": {
        "console_dev": {
            "class": "logging.StreamHandler",
            "level": "DEBUG",
            "filters": ["require_debug_true"],
            "formatter": "dev",
        },
        "console_prod": {
            "class": "logging.StreamHandler",
            "level": LOG_LEVEL,
            "filters": ["require_debug_false"],
            "formatter": "prod",
        },
    },
    "root": {
        "handlers": ["console_dev", "console_prod"],
        "level": LOG_LEVEL,
    },
    "loggers": {
        "django": {
            "handlers": ["console_dev", "console_prod"],
            "level": DJANGO_LOG_LEVEL,
            "propagate": False,
        },
        "django.request": {
            "handlers": ["console_dev", "console_prod"],
            "level": "WARNING",
            "propagate": False,
        },
        "job_scraper": {
            "handlers": ["console_dev", "console_prod"],
            "level": LOG_LEVEL,
            "propagate": False,
        },
        "apscheduler": {
            "handlers": ["console_dev", "console_prod"],
            "level": "INFO",
            "propagate": False,
        },
    },
}
