# Generated by Django 5.0.7 on 2026-04-15 11:45

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("job_scraper", "0002_customwebsite"),
    ]

    operations = [
        migrations.AddField(
            model_name="job",
            name="continent",
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name="job",
            name="expertise_tags",
            field=models.TextField(
                blank=True, help_text="Comma-separated expertise/skills"
            ),
        ),
        migrations.AddField(
            model_name="job",
            name="is_rfp",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="job",
            name="needs_summary",
            field=models.TextField(
                blank=True, help_text="AI-generated summary of client needs"
            ),
        ),
        migrations.CreateModel(
            name="Contact",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=200)),
                ("title", models.CharField(blank=True, max_length=200)),
                ("email", models.EmailField(blank=True, max_length=254, null=True)),
                ("phone", models.CharField(blank=True, max_length=50)),
                ("linkedin_url", models.URLField(blank=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "job",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="contacts",
                        to="job_scraper.job",
                    ),
                ),
            ],
            options={
                "ordering": ["-created_at"],
            },
        ),
    ]
