# Generated by Django 5.0.7 on 2026-04-16 08:21

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("job_scraper", "0003_job_continent_job_expertise_tags_job_is_rfp_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="customwebsite",
            name="use_stealth",
            field=models.BooleanField(
                default=False,
                help_text="Use high-protection stealth browser (seleniumbase) for this site",
            ),
        ),
    ]
