# Generated by Django 5.0.7 on 2026-04-16 12:08

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("job_scraper", "0004_customwebsite_use_stealth"),
    ]

    operations = [
        migrations.CreateModel(
            name="ScraperExecutionLog",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("timestamp", models.DateTimeField(auto_now_add=True)),
                ("jobs_found", models.IntegerField(default=0)),
                ("error_message", models.TextField(blank=True)),
                (
                    "screenshot",
                    models.FileField(
                        blank=True, null=True, upload_to="artifacts/screenshots/"
                    ),
                ),
                (
                    "html_dump",
                    models.FileField(
                        blank=True, null=True, upload_to="artifacts/html_dumps/"
                    ),
                ),
                (
                    "website",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="execution_logs",
                        to="job_scraper.customwebsite",
                    ),
                ),
            ],
            options={
                "ordering": ["-timestamp"],
            },
        ),
    ]
