# Generated by Django 5.0.7 on 2026-04-16 12:16

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("job_scraper", "0005_scraperexecutionlog"),
    ]

    operations = [
        migrations.AddField(
            model_name="scraperexecutionlog",
            name="scraper_type",
            field=models.CharField(
                choices=[
                    ("requests", "Standard (Requests)"),
                    ("seleniumbase", "Stealth (seleniumbase)"),
                ],
                default="requests",
                max_length=20,
            ),
        ),
    ]
