# Generated by Django 5.0.7 on 2026-04-16 15:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("job_scraper", "0006_scraperexecutionlog_scraper_type"),
    ]

    operations = [
        migrations.AddField(
            model_name="customwebsite",
            name="api_company_key",
            field=models.CharField(
                blank=True, help_text="JSON key for company", max_length=100
            ),
        ),
        migrations.AddField(
            model_name="customwebsite",
            name="api_description_key",
            field=models.CharField(
                blank=True, help_text="JSON key for description", max_length=100
            ),
        ),
        migrations.AddField(
            model_name="customwebsite",
            name="api_jobs_path",
            field=models.CharField(
                blank=True,
                help_text="Key path to the list of jobs (e.g. 'data')",
                max_length=255,
            ),
        ),
        migrations.AddField(
            model_name="customwebsite",
            name="api_location_key",
            field=models.CharField(
                blank=True, help_text="JSON key for location", max_length=100
            ),
        ),
        migrations.AddField(
            model_name="customwebsite",
            name="api_title_key",
            field=models.CharField(
                blank=True, help_text="JSON key for job title", max_length=100
            ),
        ),
        migrations.AddField(
            model_name="customwebsite",
            name="api_url_key",
            field=models.CharField(
                blank=True, help_text="JSON key for job URL", max_length=100
            ),
        ),
        migrations.AddField(
            model_name="customwebsite",
            name="is_api",
            field=models.BooleanField(
                default=False, help_text="Set to true if this is a JSON API endpoint"
            ),
        ),
    ]
