# Generated by Django 5.0.7 on 2026-04-16 15:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("job_scraper", "0007_customwebsite_api_company_key_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="scraperexecutionlog",
            name="scraper_type",
            field=models.CharField(
                choices=[
                    ("requests", "Standard (Requests)"),
                    ("playwright", "Stealth (Playwright)"),
                    ("api", "JSON API"),
                ],
                default="requests",
                max_length=20,
            ),
        ),
    ]
