# Generated by Django 5.0.7 on 2026-04-22 08:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("job_scraper", "0008_alter_scraperexecutionlog_scraper_type"),
    ]

    operations = [
        migrations.AddConstraint(
            model_name="contact",
            constraint=models.UniqueConstraint(
                fields=("job", "name"), name="unique_job_contact_name"
            ),
        ),
    ]
