# Generated by Django 5.0.7 on 2026-04-23 18:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("job_scraper", "0009_contact_unique_job_contact_name"),
    ]

    operations = [
        migrations.AlterField(
            model_name="customwebsite",
            name="use_stealth",
            field=models.BooleanField(
                default=False,
                help_text="Use high-protection stealth browser (SeleniumBase UC mode) for this site",
            ),
        ),
        migrations.AlterField(
            model_name="scraperexecutionlog",
            name="scraper_type",
            field=models.CharField(
                choices=[
                    ("requests", "Standard (Requests)"),
                    ("seleniumbase", "Stealth (SeleniumBase)"),
                    ("api", "JSON API"),
                ],
                default="requests",
                max_length=20,
            ),
        ),
    ]
